apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "${CLUSTER_NAME}"
  region: "${AWS_REGION}"
  version: "${KUBERNETES_VERSION}"
  tags:
    project: "${CLUSTER_NAME}"
    environment: "${ENVIRONMENT}"
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: s3-access
        namespace: default
        labels: {aws-usage: "application"}
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
    - metadata:
        name: external-dns
        namespace: kube-system
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cert-manager
        namespace: cert-manager
      wellKnownPolicies:
        certManager: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
        labels: {aws-usage: "cluster-ops"}
      wellKnownPolicies:
        autoScaler: true
    - metadata:
        name: autoscaler-service
        namespace: kube-system
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "autoscaling:DescribeAutoScalingGroups"
              - "autoscaling:DescribeAutoScalingInstances"
              - "autoscaling:DescribeLaunchConfigurations"
              - "autoscaling:DescribeTags"
              - "autoscaling:SetDesiredCapacity"
              - "autoscaling:TerminateInstanceInAutoScalingGroup"
              - "ec2:DescribeLaunchTemplateVersions"
            Resource: '*'
# We are going to use existing VPC
vpc:
  id: "vpc-0463def14f555a7ed"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-1a: {id: subnet-02c7bfb3450e3cb14}
      us-east-1b: {id: subnet-049a6317b90706776}
      us-east-1c: {id: subnet-0920a1dff5c03103b}
    private:
      us-east-1d: {id: subnet-0f8836c96b7d3305f}
      us-east-1f: {id: subnet-0b7faf7a4a01e03ff}
